# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf0c09a7c638923535d0a3403f5948620566488f084ee5c0f6aaef455e329d154cf252507f574fc5ab099f934a086eb778a5a5ab20c161175c1276727a21552

test:
  secret_key_base: ea7b5eb12e4fb9e4569433a88d844f19733850d0810f21a0423151d66cc04d1465ed63d77eda4ddd0b5afc2d42d45c1aedff2bc02b7b4b4e05e3811a72f8ffb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
